import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { log } from '../core/logger.js';

export interface CamofoxCookie {
  domain: string;
  name: string;
  value: string;
  httpOnly?: boolean;
  secure?: boolean;
  path?: string;
  expires?: number;
}

export interface ExportOptions {
  tmpDir: string;
  fetchCookies: (userId: string) => Promise<CamofoxCookie[]>;
  /**
   * Optional: re-establishes the Camofox browser session for `userId` so that
   * /sessions/:userId/cookies stops returning 409. Called once after a 409
   * before a final fetchCookies retry.
   */
  wakeBrowser?: (userId: string) => Promise<void>;
  userId?: string;
}

export interface ExportResult {
  cookieFilePath: string;
  cookieCount: number;
  error?: { code: 'COOKIE_FETCH_FAILED'; message: string };
}

function hostMatches(cookieDomain: string, targetHost: string): boolean {
  // Cookies set on `.example.com` apply to `example.com` and every subdomain
  // (including `www.example.com`). Without the explicit `www.` fallback,
  // `hostMatches('.youtube.com', 'www.youtube.com')` would return false even
  // though the cookie was set on the parent domain — yt-dlp would load an
  // empty cookie jar and the platform would treat us as anonymous.
  const d = cookieDomain.toLowerCase().replace(/^\./, '');
  const h = targetHost.toLowerCase().replace(/^\./, '');
  return d === h || h === `www.${d}` || h.endsWith(`.${d}`);
}

function toNetscapeLine(c: CamofoxCookie): string {
  const clean = (s: string): string => s.replace(/[\t\n\r]/g, ' ');
  let domain = clean(c.domain);
  let domainSpecified = domain.startsWith('.');
  if (!domainSpecified) {
    domain = `.${domain}`;
    domainSpecified = true;
  }
  const httpOnly = c.httpOnly ? 'TRUE' : 'FALSE';
  const secure = c.secure ? 'TRUE' : 'FALSE';
  const cookiePath = clean(c.path ?? '/');
  const expires = c.expires && c.expires > 0 ? Math.floor(c.expires) : 0;
  const name = clean(c.name);
  const value = clean(c.value);
  return [domain, domainSpecified ? 'TRUE' : 'FALSE', secure, cookiePath, expires, name, value].join('\t');
}

export async function exportCookiesForHost(
  targetHost: string,
  opts: ExportOptions,
): Promise<ExportResult> {
  const safeHost = targetHost.replace(/[^a-z0-9.-]/gi, '_');
  const cookieFilePath = path.join(opts.tmpDir, `camofox_cookies_${safeHost}.txt`);
  let cookies: CamofoxCookie[] = [];
  const userId = opts.userId ?? 'default';
  log.info('video.cookies.using-userid', { userId, targetHost });
  try {
    cookies = await opts.fetchCookies(userId);
  } catch (err) {
    // Camofox returns 409 ("No active session") when the IDLE_TIMEOUT (~30 min)
    // has fired and the session is detached from the user. `wakeBrowser`
    // creates a tab scoped to the user + a stable sessionKey, which Camofox
    // re-binds to the user's session. Without this retry we'd hand yt-dlp an
    // empty cookie jar on every download past the idle window.
    if (opts.wakeBrowser) {
      try {
        log.info('video.cookies.wake-browser', { targetHost, userId });
        await opts.wakeBrowser(userId);
        cookies = await opts.fetchCookies(userId);
      } catch (retryErr) {
        const message = err instanceof Error ? err.message : String(err);
        const retryMessage = retryErr instanceof Error ? retryErr.message : String(retryErr);
        log.error('video.cookies.wake-failed', { targetHost, message, retryMessage });
        await fs.writeFile(cookieFilePath, '# Netscape HTTP Cookie File\n', 'utf8');
        return { cookieFilePath, cookieCount: 0, error: { code: 'COOKIE_FETCH_FAILED', message: message + ' / retry: ' + retryMessage } };
      }
    } else {
      const message = err instanceof Error ? err.message : String(err);
      log.error('video.cookies.fetch-failed', { targetHost, message });
      await fs.writeFile(cookieFilePath, '# Netscape HTTP Cookie File\n', 'utf8');
      return { cookieFilePath, cookieCount: 0, error: { code: 'COOKIE_FETCH_FAILED', message } };
    }
  }
  const filtered = cookies.filter((c) => hostMatches(c.domain, targetHost));
  const header = '# Netscape HTTP Cookie File\n# Generated by camofox-opencli gateway\n\n';
  const body = filtered.map(toNetscapeLine).join('\n') + (filtered.length ? '\n' : '');
  await fs.writeFile(cookieFilePath, header + body, 'utf8');
  log.info('video.cookies.exported', {
    host: targetHost,
    cookieFilePath,
    totalCookiesFromJar: cookies.length,
    matched: filtered.length,
    matchedNames: filtered.map((c) => c.name).slice(0, 20),
  });
  return { cookieFilePath, cookieCount: filtered.length, error: undefined };
}